### ISSUE TITLE
Template change didn't update during development time!

### ISSUE THREAD

**Issue by Ok9xNirab** [WPDrill/core#1]
Hi,
I'm developing **Weather Information** Plugin.
The twig template didn't update if it's already cached!

https://github.com/WPDrill/core/blob/3799d77f0b7f33af4876b30734c28428233f990e/src/ViewManager.php#L27

I think, it's better to disable cache on development mode.

**Thanks**

**Comment by nahid** [comment]
The issue has been solved in this commit

Commit: https://github.com/WPDrill/core/commit/0ff7125876709870bc2f9e163562d0d7d5a6a07a
